// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Code      string `json:"code,optional,optional"`
	AvatarUrl string `json:"avatarUrl,optional"`
	Name      string `json:"name,optional"`
}

type LoginReply struct {
	ID           string `json:"id,optional"`
	Name         string `json:"name,optional"`
	AccessToken  string `json:"accessToken,optional"`
	AccessExpire int    `json:"accessxpire,optional"`
	RefreshAfter int    `json:"refreshAfter,optional"`
	AvatarUrl    string `json:"avatarUrl"`
}

type Book struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	CreatedTime int    `json:"createdTime"`
	Tp          int    `json:"tp"`
	Uid         string `json:"uid"`
}

type Tag struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	CreatedTime int    `json:"createdTime"`
	Priority    int    `json:"priority"`
}

type Journal struct {
	ID     string `json:"id,optional"`
	Name   string `json:"name,optional"`
	Date   int    `json:"date,optional"`
	Tid    string `json:"tid,optional"`
	Tname  string `json:"tname,optional"`
	Amount string `json:"amount,optional"`
	Record string `json:"record,optional"`
	BookID string `json:"bookID,optional" form:"bookID"`
	Uid    string `json:"uid,optional"`
}
