// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Code      string `json:"code,omitempty,optional"`
	AvatarUrl string `json:"avatarUrl,optional"`
	Name      string `json:"name,optional"`
}

type LoginReply struct {
	ID           string `json:"id,omitempty"`
	Name         string `json:"name,omitempty"`
	AccessToken  string `json:"accessToken,omitempty"`
	AccessExpire int    `json:"accessxpire,omitempty"`
	RefreshAfter int    `json:"refreshAfter,omitempty"`
	AvatarUrl    string `json:"avatarUrl"`
}

type Book struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	CreatedTime int    `json:"createdTime"`
	Tp          int    `json:"tp"`
	Uid         string `json:"uid"`
}

type Tag struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	CreatedTime int    `json:"createdTime"`
	Priority    int    `json:"priority"`
}

type Journal struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Date   int    `json:"date"`
	Tid    string `json:"tid"`
	Tname  string `json:"tname"`
	Amount int    `json:"amount"`
	Record string `json:"record"`
	BookID string `json:"BookID"`
	Uid    string `json:"uid"`
}
