// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Code      string `json:"code,omitempty,optional"`
	AvatarUrl string `json:"avatarUrl,optional"`
	Name      string `json:"name,optional"`
}

type LoginReply struct {
	Id           int    `json:"id,omitempty"`
	Name         string `json:"name,omitempty"`
	AccessToken  string `json:"accessToken,omitempty"`
	AccessExpire int    `json:"accessxpire,omitempty"`
	RefreshAfter int    `json:"refreshAfter,omitempty"`
	AvatarUrl    string `json:"avatarUrl"`
}

type AcBook struct {
	Id          int    `json:"id"`
	Name        string `json:"name"`
	CreatedTime int    `json:"createdTime"`
	Tp          int    `json:"tp"`
	Uid         int    `json:"uid"`
}

type Tag struct {
	Id          int    `json:"id"`
	Name        string `json:"name"`
	CreatedTime int    `json:"createdTime"`
	Priority    int    `json:"priority"`
}

type Journal struct {
	Id       int    `json:"id"`
	Name     string `json:"name"`
	Date     int    `json:"date"`
	Tid      int    `json:"tid"`
	Tname    string `json:"tname"`
	Amount   int    `json:"amount"`
	Notes    string `json:"notes"`
	AcBookId int    `json:"ac_book_id"`
	Uid      int    `json:"uid"`
}
