// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"huahua_account_backend/account/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: loginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ac_book",
				Handler: acBookListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tag",
				Handler: tagListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tag",
				Handler: createTagHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/journal",
				Handler: createJournalHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/journal",
				Handler: journalListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
